//
//  MAXAdvertANE.h
//  MAXSDK
//
//  Created by 洋吴 on 2019/9/10.
//  Copyright © 2020 洋吴. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "MAXAdvertANEUtils.h"
#import "MAXFunctions.h"


FREContext MAXANEEventContext;

#pragma mark - sdk
MAX_ANE_FUNCTION(INIT_SDK);
MAX_ANE_FUNCTION(SET_USER_CONTENT);
MAX_ANE_FUNCTION(SET_IS_AGE_RESTRICT_USER);

#pragma mark - interstitial
MAX_ANE_FUNCTION(LOAD_INTERSTITIAL);
MAX_ANE_FUNCTION(SET_INTERSTITIAL_EXTRA_PARAMETER);
MAX_ANE_FUNCTION(ISREADY_INTERSTITIAL);
MAX_ANE_FUNCTION(SHOW_INTERSTITIAL);
MAX_ANE_FUNCTION(SHOW_INTERSTITIAL_FOR_PLACEMENT);

#pragma mark - rewardVideo
MAX_ANE_FUNCTION(LOAD_REWARDVIDEO);
MAX_ANE_FUNCTION(SET_REWARDVIDEO_EXTRA_PARAMETER);
MAX_ANE_FUNCTION(ISREADY_REWARDVIDEO);
MAX_ANE_FUNCTION(SHOW_REWARDVIDEO);
MAX_ANE_FUNCTION(SHOW_REWARDVIDEO_FOR_PLACEMENT);

#pragma mark - banner
MAX_ANE_FUNCTION(LOAD_BANNER);
MAX_ANE_FUNCTION(SET_BANNER_EXTRA_PARAMETER);
MAX_ANE_FUNCTION(HIDE_BANNER);
MAX_ANE_FUNCTION(SHOW_BANNER);












